# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: turnaround-server-build

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create secret files
        working-directory: ./src/main/resources
        run: |
          touch application.yml
          touch application-prod.yml
          touch application-aws.yml
          touch application-firebase.yml
          touch application-jwt.yml
          touch application-slack.yml
          echo "${{ secrets.APPLICATION_YML }}" >> application.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" >> application-prod.yml
          echo "${{ secrets.APPLICATION_AWS_YML }}" >> application-aws.yml
          echo "${{ secrets.APPLICATION_FIREBASE_YML }}" >> application-firebase.yml
          echo "${{ secrets.APPLICATION_JWT_YML }}" >> application-jwt.yml
          echo "${{ secrets.APPLICATION_SLACK_YML }}" >> application-slack.yml
          
          mkdir firebase
          touch ./firebase/firebase_service_key.json
          echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
          sed -i 's/#/"/g' ./firebase/firebase_service_key.json

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash
